In [1]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv(r'C:\Users\Malini\Downloads\Salary.csv')
print(df)

     age  Salary  Status
0     33   46790       1
1     39   77464       1
2     40   68252       1
3     33   99233       1
4     26   60913       1
..   ...     ...     ...
395   41   99241       1
396   34   60921       1
397   33   84776       1
398   44   71591       1
399   45   54768       1

[400 rows x 3 columns]


In [4]:
print(df.head)

<bound method NDFrame.head of      age  Salary  Status
0     33   46790       1
1     39   77464       1
2     40   68252       1
3     33   99233       1
4     26   60913       1
..   ...     ...     ...
395   41   99241       1
396   34   60921       1
397   33   84776       1
398   44   71591       1
399   45   54768       1

[400 rows x 3 columns]>


In [8]:
#segregatting X and Y values

In [5]:
x=df.iloc[:,:-1].values
x

array([[   33, 46790],
       [   39, 77464],
       [   40, 68252],
       [   33, 99233],
       [   26, 60913],
       [   25, 84768],
       [   36, 71583],
       [   37, 54760],
       [   25, 41304],
       [   39, 97210],
       [   25, 70871],
       [   33, 57273],
       [   32, 85251],
       [   38, 75964],
       [   25, 57008],
       [   33, 44058],
       [   36, 49474],
       [   29, 49352],
       [   30, 33006],
       [   32, 76589],
       [   26, 61065],
       [   39, 63746],
       [   31, 51051],
       [   26, 54590],
       [   35, 31704],
       [   27, 87151],
       [   40, 89929],
       [   36, 84107],
       [   33, 70218],
       [   30, 64480],
       [   25, 75572],
       [   29, 27030],
       [   39, 79232],
       [   29, 85123],
       [   28, 97708],
       [   33, 49327],
       [   36, 95438],
       [   25, 86913],
       [   30, 38001],
       [   35, 61762],
       [   32, 26350],
       [   27, 33500],
       [   37, 74364],
       [   

In [7]:
Y=df.iloc[:,-1].values
Y

array([1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1,

In [10]:
#splitting data into train and test

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,Y_train,Y_test= train_test_split(x,Y,test_size=0.25,)

In [ ]:
#feature scalling

In [16]:
from sklearn.preprocessing import StandardScaler
SC=StandardScaler()
x_train=SC.fit_transform(x_train)
x_test=SC.transform(x_test)
print(x_test)

[[-1.83378579e+00 -4.61785472e-01]
 [-1.46319924e+00  3.13209571e-01]
 [-1.64849251e+00  1.11418705e+00]
 [ 1.50149318e+00  5.63979445e-01]
 [ 1.91469719e-02  2.81075990e-01]
 [-9.07319409e-01 -4.87866326e-01]
 [ 7.60320077e-01 -9.92850715e-01]
 [-3.51439581e-01 -4.58696613e-02]
 [-1.83378579e+00 -3.69075417e-01]
 [ 1.91469719e-02 -7.39866429e-01]
 [-3.51439581e-01 -1.23695422e-03]
 [ 1.87207973e+00  1.60952644e+00]
 [-3.51439581e-01  1.63398340e+00]
 [-2.01907907e+00  9.96921625e-01]
 [-1.83378579e+00 -4.88112372e-01]
 [ 5.75026801e-01 -7.46804921e-01]
 [ 3.89733524e-01  1.52208177e+00]
 [-9.07319409e-01 -4.60172888e-02]
 [ 5.75026801e-01  5.94784378e-01]
 [ 1.13090663e+00  1.60932961e+00]
 [ 1.50149318e+00  1.84379993e-01]
 [-1.27790596e+00 -1.84431679e+00]
 [-1.46319924e+00 -3.68976999e-01]
 [-1.09261269e+00  1.63378656e+00]
 [ 7.60320077e-01  5.63782608e-01]
 [-1.66146304e-01 -1.00628482e+00]
 [ 1.91469719e-02 -3.55936571e-01]
 [-7.22026133e-01  1.10281973e+00]
 [-7.22026133e-01 -4

In [11]:
#algorithm

In [17]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,Y_train)

LogisticRegression()

In [12]:
#prediction for all the test data

In [25]:
y_pred=model.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),Y_test.reshape(len(Y_test),1)),1))

[[0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [0 1]
 [1 1]
 [0 1]
 [1 1]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 0]
 [0 1]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [1 1]]


In [20]:
y_pred=model.predict(x_test)
print(y_pred)

[0 1 1 1 1 1 0 1 1 0 1 1 1 1 0 0 1 1 1 1 1 0 1 1 1 0 1 1 1 1 0 0 1 1 1 1 0
 1 0 1 0 0 0 0 0 0 1 0 1 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 0 1 1 0 1 0 1 0 0 1
 0 0 0 1 0 1 1 1 1 0 1 1 1 0 1 1 1 1 0 0 0 1 0 0 1 1]


In [22]:
#confusion matrix and accuracy

In [27]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(Y_test,y_pred)
print("confussion matrix:",cm)
print("accuracy of the model:{0}%".format(accuracy_score(Y_test,y_pred)*100))

confussion matrix: [[23 11]
 [19 47]]
accuracy of the model:70.0%


In [28]:
#predicting whether new customer with age & salary will buy or not

In [30]:
age=int(input("enter new customer age:"))
sal=int(input("enter new customer sal:"))
newcust=[[age,sal]]
result=model.predict(SC.transform(newcust))
print(result)
if result ==1:
    print("customer will buy")
else: 
    print("customer won't buy")

enter new customer age:45
enter new customer sal:500000
[1]
customer will buy
